[platformio]
default_envs = uno_r4, xiao_1, xiao_2

[env]
framework = arduino
monitor_speed = 115200
monitor_filters = time
build_flags =
  -I include
  -I variants
  -I src

[env:uno_r4]
platform = renesas-ra
board = uno_r4_wifi
build_flags =
  ${env.build_flags}
  -DBOARD_UNO_R4_WIFI
  -DDEVICE_UNO_R4

[env:xiao_1]
platform = espressif32
board = seeed_xiao_esp32s3
build_flags =
  ${env.build_flags}
  -DBOARD_XIAO_ESP32S3
  -DDEVICE_XIAO_1

[env:xiao_2]
platform = espressif32
board = seeed_xiao_esp32s3
build_flags =
  ${env.build_flags}
  -DBOARD_XIAO_ESP32S3
  -DDEVICE_XIAO_2
